export const SUBMIT_CREDENTIALS = 'SUBMIT_CREDENTIALS';
export const SUBMIT_CREDENTIALS_SUCCESS = 'SUBMIT_CREDENTIALS_SUCCESS';
export const SUBMIT_CREDENTIALS_ERROR = 'SUBMIT_CREDENTIALS_ERROR';

export const SUBMIT_LOGIN_CREDENTIALS = 'SUBMIT_LOGIN_CREDENTIALS';
export const SUBMIT_LOGIN_CREDENTIALS_SUCCESS = 'SUBMIT_LOGIN_CREDENTIALS_SUCCESS';
export const SUBMIT_LOGIN_CREDENTIALS_ERROR = 'SUBMIT_LOGIN_CREDENTIALS_ERROR';

export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
